#
# WARNING: To install Immich, follow our guide: https://docs.immich.app/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich_server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-v2}
    depends_on:
      - immich_postgres
      - immich_redis
    ports:
      - "2283:3001"
    env_file:
      - .env
    environment:
      - UPLOAD_LOCATION=/usr/src/app/upload
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload

  immich_machine_learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-v2}
    depends_on:
      - immich_server
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload

  immich_postgres:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data

  immich_redis:
    image: valkey/valkey:8
    volumes:
      - redis_data:/data

volumes:
  redis_data:
