services:
  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
      # - LOG_LEVEL=info   # opcional
      # - PORT=5055        # opcional; por defecto es 5055
    ports:
      - "127.0.0.1:15055:5055"
    volumes:
      - /srv/storage/services/jellyseer/config:/app/config
